// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0787wXlD7GQihh5kjOBS5wS_20bmwb8',
    appId: '1:612830646559:web:5b13f30ce8f97aa3e0e02a',
    messagingSenderId: '612830646559',
    projectId: 'wedjhi',
    authDomain: 'wedjhi.firebaseapp.com',
    storageBucket: 'wedjhi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FVkyPPnkZxf5vCmGIHscbgsRJVZWTCc',
    appId: '1:612830646559:android:490814ff6a34cd1ce0e02a',
    messagingSenderId: '612830646559',
    projectId: 'wedjhi',
    storageBucket: 'wedjhi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM0787wXlD7GQihh5kjOBS5wS_20bmwb8',
    appId: '1:612830646559:web:1aa2da193bd7f419e0e02a',
    messagingSenderId: '612830646559',
    projectId: 'wedjhi',
    authDomain: 'wedjhi.firebaseapp.com',
    storageBucket: 'wedjhi.firebasestorage.app',
  );
}
